// Spoken Vietnamese names for symbols used inside on-screen prompts.
// Generated from assets/data/vietnamese/words.json plus shape/arrow names;
// keep in sync with tools/generate_missing_audio.py (it reads exported text).
const Map<String, String> kEmojiSpokenNames = {
  "—": ",",
  "←": "trái",
  "↑": "lên",
  "→": "phải",
  "↓": "xuống",
  "−": "trừ",
  "■": "hình vuông",
  "□": "hình vuông",
  "▬": "hình chữ nhật",
  "▲": "tam giác",
  "△": "tam giác",
  "○": "hình tròn",
  "●": "hình tròn",
  "◯": "hình tròn",
  "◽": "ô nhỏ",
  "☀": "mặt trời",
  "☁": "đám mây",
  "☂": "cái ô",
  "⚕": "y tế",
  "⚙": "máy móc",
  "⚡": "tia chớp",
  "⚪": "chấm trắng",
  "⚫": "chấm đen",
  "⚽": "quả bóng",
  "⛑": "mũ bảo hiểm",
  "⛰": "núi",
  "⛱": "cái dù",
  "⛵": "thuyền",
  "✂": "cây kéo",
  "✈": "máy bay",
  "✉": "lá thư",
  "✋": "bàn tay",
  "✍": "viết",
  "✏": "bút chì",
  "✨": "lấp lánh",
  "❄": "bông tuyết",
  "❤": "trái tim",
  "⬜": "ô trắng",
  "⬭": "hình bầu dục",
  "⭐": "ngôi sao",
  "⭕": "hình tròn",
  "🌃": "ban đêm",
  "🌅": "buổi sáng",
  "🌈": "cầu vồng",
  "🌉": "cây cầu",
  "🌊": "sóng biển",
  "🌌": "bầu trời",
  "🌕": "trăng tròn",
  "🌖": "trăng khuyết",
  "🌗": "nửa vầng trăng",
  "🌙": "mặt trăng",
  "🌜": "trăng khuyết",
  "🌞": "mặt trời",
  "🌧": "mưa",
  "🌱": "mầm cây",
  "🌲": "rừng",
  "🌳": "cái cây",
  "🌸": "bông hoa",
  "🌺": "hoa dâm bụt",
  "🌻": "hoa hướng dương",
  "🌼": "bông hoa cúc",
  "🌾": "bông lúa",
  "🌿": "cành lá",
  "🍀": "cỏ bốn lá",
  "🍃": "lá cây",
  "🍇": "quả nho",
  "🍈": "quả dưa",
  "🍉": "quả dưa hấu",
  "🍊": "quả cam",
  "🍌": "quả chuối",
  "🍎": "quả táo",
  "🍐": "quả lê",
  "🍒": "quả anh đào",
  "🍓": "quả dâu tây",
  "🍖": "miếng thịt",
  "🍚": "cơm",
  "🍜": "phở",
  "🍞": "bánh mì",
  "🍦": "cây kem",
  "🍩": "bánh vòng",
  "🍪": "bánh quy",
  "🍬": "viên kẹo",
  "🍮": "chè",
  "🍲": "nồi canh",
  "🍵": "trà",
  "🎀": "cái nơ",
  "🎁": "hộp quà",
  "🎈": "bóng bay",
  "🎒": "cặp sách",
  "🎠": "xích đu",
  "🎤": "micro",
  "🎨": "màu vẽ",
  "🎲": "xúc xắc",
  "🎵": "âm nhạc",
  "🎸": "đàn ghi ta",
  "🎹": "đàn piano",
  "🎺": "kèn",
  "🎻": "đàn vi ô lông",
  "🎾": "quả bóng tennis",
  "🏀": "bóng rổ",
  "🏃": "chạy",
  "🏊": "bơi",
  "🏖": "bãi biển",
  "🏞": "sông",
  "🏠": "ngôi nhà",
  "🏥": "bệnh viện",
  "🏫": "trường học",
  "🐔": "con gà",
  "🐕": "con chó",
  "🐘": "con voi",
  "🐝": "con ong",
  "🐟": "con cá",
  "🐠": "con cá",
  "🐢": "con rùa",
  "🐣": "gà con",
  "🐥": "gà con",
  "🐦": "con chim",
  "🐧": "chim cánh cụt",
  "🐭": "con chuột",
  "🐮": "con bò",
  "🐰": "con thỏ",
  "🐱": "con mèo",
  "🐴": "con ngựa",
  "🐶": "con chó",
  "🐷": "con heo",
  "🐸": "con ếch",
  "🐾": "dấu chân",
  "👁": "mắt",
  "👂": "tai",
  "👃": "mũi",
  "👄": "miệng",
  "👋": "xin chào",
  "👕": "cái áo",
  "👜": "túi",
  "👦": "bạn trai",
  "👧": "bạn gái",
  "👨": "bố",
  "👨‍⚕": "bác sĩ",
  "👨‍🌾": "nông dân",
  "👨‍👩‍👧": "gia đình",
  "👩": "mẹ",
  "👩‍🏫": "cô giáo",
  "👩‍💼": "cô hiệu trưởng",
  "👮": "công an",
  "👴": "ông",
  "👵": "bà",
  "👶": "em bé",
  "💇": "tóc",
  "💡": "bóng đèn",
  "💦": "suối",
  "💧": "giọt nước",
  "💨": "gió",
  "💪": "khỏe",
  "📄": "tờ giấy",
  "📏": "thước kẻ",
  "📐": "thước ê ke",
  "📖": "quyển sách",
  "📚": "chồng sách",
  "📝": "bài tập",
  "📦": "cái hộp",
  "📯": "còi",
  "🔔": "chuông",
  "🔢": "số",
  "🔤": "chữ",
  "🔥": "ngọn lửa",
  "🔦": "đèn pin",
  "🔴": "chấm đỏ",
  "🔵": "chấm xanh dương",
  "🔷": "hình thoi",
  "🔺": "tam giác đỏ",
  "🔻": "tam giác ngược",
  "🖍": "tô màu",
  "🗄": "cái tủ",
  "😄": "cười",
  "😊": "vui",
  "😢": "buồn",
  "😭": "khóc",
  "😴": "ngủ",
  "🙆": "vâng",
  "🙇": "xin lỗi",
  "🙏": "cảm ơn",
  "🚂": "tàu hỏa",
  "🚆": "tàu hỏa",
  "🚌": "xe buýt",
  "🚎": "xe điện",
  "🚕": "xe taxi",
  "🚗": "xe ô tô",
  "🚦": "đèn giao thông",
  "🚩": "lá cờ",
  "🚪": "cánh cửa",
  "🚲": "xe đạp",
  "🚶": "đi",
  "🛏": "cái giường",
  "🛑": "biển dừng",
  "🛒": "chợ",
  "🛝": "công viên",
  "🛣": "đường",
  "🟠": "chấm cam",
  "🟡": "chấm vàng",
  "🟢": "chấm xanh lá",
  "🟣": "chấm tím",
  "🟤": "chấm nâu",
  "🟥": "ô đỏ",
  "🟦": "ô xanh dương",
  "🟧": "ô cam",
  "🟨": "ô vàng",
  "🟩": "ô xanh lá",
  "🤗": "ôm",
  "🤝": "bạn thân",
  "🤸": "nhào lộn",
  "🥁": "cái trống",
  "🥄": "cái thìa",
  "🥖": "bánh mì",
  "🥚": "trứng",
  "🥛": "sữa",
  "🥟": "bánh bao",
  "🥢": "đôi đũa",
  "🥣": "cái chén",
  "🥤": "uống",
  "🥬": "rau",
  "🥭": "quả xoài",
  "🦆": "con vịt",
  "🦋": "con bướm",
  "🦌": "con hươu",
  "🦎": "thằn lằn",
  "🦐": "con tôm",
  "🦒": "hươu cao cổ",
  "🦓": "ngựa vằn",
  "🦶": "bàn chân",
  "🦷": "răng",
  "🧁": "bánh nướng",
  "🧂": "muối",
  "🧒": "em bé",
  "🧢": "cái mũ",
  "🧧": "tết",
  "🧭": "la bàn",
  "🧸": "gấu bông",
  "🧻": "cuộn giấy",
  "🧼": "xà phòng",
  "🧽": "miếng bọt biển",
  "🩷": "màu hồng",
  "🪁": "con diều",
  "🪆": "búp bê",
  "🪈": "cây sáo",
  "🪑": "cái ghế",
  "🪢": "nhảy dây",
  "🪥": "bàn chải",
  "🪨": "hòn đá",
  "🪭": "cái quạt",
  "🪵": "khúc gỗ",
  "🪶": "lông",
  "🪺": "tổ chim",
  "🪽": "cánh",
  "🫄": "bụng",
  "🫖": "ấm trà",
  "🫧": "bong bóng",
};
