#!/usr/bin/env python3
"""Build audio_content_v3.json and audio_v3_preflight.md from repository data.

Does not generate WAV files. Does not modify assets/audio.
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

# Curriculum letter names/sounds — copied from lib/core/audio/vietnamese_speech_catalog.dart
# Do not invent Â → "ớ" or B name → "bờ". Name vs sound stay as taught in-app.
VI_LETTERS = {
    "a": ("A", "a", "a"),
    "aw": ("Ă", "ă", "ă"),
    "aa": ("Â", "â", "â"),
    "b": ("B", "bê", "bờ"),
    "c": ("C", "xê", "cờ"),
    "d": ("D", "dê", "dờ"),
    "dd": ("Đ", "đê", "đờ"),
    "e": ("E", "e", "e"),
    "ee": ("Ê", "ê", "ê"),
    "g": ("G", "giê", "gờ"),
    "h": ("H", "hát", "hờ"),
    "i": ("I", "i", "i"),
    "k": ("K", "ca", "cờ"),
    "l": ("L", "e-lờ", "lờ"),
    "m": ("M", "em-mờ", "mờ"),
    "n": ("N", "en-nờ", "nờ"),
    "o": ("O", "o", "o"),
    "oo": ("Ô", "ô", "ô"),
    "ow": ("Ơ", "ơ", "ơ"),
    "p": ("P", "pê", "pờ"),
    "q": ("Q", "quy", "quờ"),
    "r": ("R", "e-rờ", "rờ"),
    "s": ("S", "ét", "sờ"),
    "t": ("T", "tê", "tờ"),
    "u": ("U", "u", "u"),
    "uw": ("Ư", "ư", "ư"),
    "v": ("V", "vê", "vờ"),
    "x": ("X", "ích", "xờ"),
    "y": ("Y", "i", "i"),
}


def main() -> None:
    manifest = json.loads((ROOT / "assets/audio/audio_manifest.json").read_text(encoding="utf-8"))
    inventory = json.loads((ROOT / "tool/audio_inventory.json").read_text(encoding="utf-8"))
    human = json.loads((ROOT / "tool/human_audio_inventory.json").read_text(encoding="utf-8"))
    rec = json.loads((ROOT / "tool/human_audio_recording_manifest.json").read_text(encoding="utf-8"))
    inv_by = {x["id"]: x for x in inventory["items"]}
    man_by = {x["id"]: x for x in manifest}
    rec_by = {x["id"]: x for x in rec["items"]}

    required = [x for x in human["items"] if x["classification"] == "HUMAN_REQUIRED"]
    items = []
    for src in required:
        audio_id = src["id"]
        inv = inv_by.get(audio_id, {})
        man = man_by.get(audio_id, {})
        path = src["asset"]
        spoken = src["text"]
        display = spoken
        category = "unknown"
        lang = "vi-VN" if src["language"] == "vi" else "ja-JP"
        profile = "vi_teacher_gentle" if src["language"] == "vi" else "ja_teacher_gentle"
        pause = 220
        if audio_id.startswith("vi_letter_") and audio_id.endswith("_name"):
            slug = audio_id[len("vi_letter_") : -len("_name")]
            glyph, name, _sound = VI_LETTERS[slug]
            display, spoken, category = glyph, name, "vietnamese_letter_name"
        elif audio_id.startswith("vi_letter_") and audio_id.endswith("_sound"):
            slug = audio_id[len("vi_letter_") : -len("_sound")]
            glyph, _name, sound = VI_LETTERS[slug]
            display, spoken, category = glyph, sound, "vietnamese_letter_sound"
        elif audio_id.startswith("ja_"):
            display = spoken
            category = "japanese_kana"
            pause = 200
        items.append(
            {
                "id": audio_id,
                "language": lang,
                "displayText": display,
                "spokenText": spoken,
                "category": category,
                "voiceProfile": profile,
                "style": "warm_kindergarten_teacher",
                "speed": 0.82 if src["language"] == "vi" else 0.88,
                "pauseAfterMs": pause,
                "priority": "critical",
                "productionPath": path,
                "currentProvider": man.get("source", src.get("current_source")),
                "currentQuality": "TTS_TEMPORARY",
                "targetQuality": "PREMIUM_AI_VOICE",
                "currentDurationMs": inv.get("duration_ms"),
                "sampleRate": inv.get("sample_rate"),
                "peakDb": inv.get("peak_db"),
                "replaceInPlace": True,
            }
        )

    content = {
        "version": 3,
        "note": "spokenText comes from ViMai Kids curriculum. displayText is the written glyph. Never label PREMIUM_AI_VOICE as HUMAN_RECORDING.",
        "productionReplacementCount": len(items),
        "protectedExistingFiles": 913 - len(items),
        "items": items,
    }
    out = ROOT / "tool" / "audio_content_v3.json"
    out.write_text(json.dumps(content, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    lines = [
        "# Audio V3 preflight — ViMai Kids",
        "",
        "Source of truth: `assets/audio/audio_manifest.json`, `tool/audio_inventory.json`, `tool/human_audio_inventory.json`, `tool/human_audio_recording_manifest.json`.",
        "No values in this file are guessed. Generated by `tool/build_audio_v3_content.py`.",
        "",
        "## Totals",
        "",
        f"- Bundled WAV / manifest records: **{len(manifest)}**",
        f"- Vietnamese: **{sum(1 for x in manifest if x['language']=='vi')}**",
        f"- Japanese: **{sum(1 for x in manifest if x['language']=='ja')}**",
        f"- Missing production files: **{inventory['counts']['REQUIRED_MISSING']}**",
        f"- Inventory status VALID: **{inventory['counts']['VALID']}**",
        f"- Inventory status UNUSED (file exists, not referenced by content JSON): **{inventory['counts']['UNUSED']}**",
        f"- Inventory invalid / NEEDS_REPLACEMENT flags: **0** (no such status in inventory)",
        f"- Clipping flags: **0**",
        f"- HUMAN_REQUIRED: **{human['counts']['HUMAN_REQUIRED']}** (VI letters 58 + JA basic kana 92)",
        f"- EXISTING_HUMAN / HUMAN_RECORDING files: **{human['counts']['EXISTING_HUMAN']}**",
        f"- TTS_ACCEPTABLE: **{human['counts']['TTS_ACCEPTABLE']}**",
        f"- NOT_NEEDED: **{human['counts']['NOT_NEEDED']}**",
        "",
        "Quality of all 913 shipped files today: **TTS_TEMPORARY** (Piper VI / Windows ja-JP bake). Not PREMIUM_AI_VOICE. Not HUMAN_RECORDING.",
        "",
        "Default V3 production replacement set = the 150 HUMAN_REQUIRED IDs. The other **763** files must be skipped.",
        "",
        "The only production phrase ID in the 913-file contract is `vi_phrase_gioi_lam` (classification TTS_ACCEPTABLE, not in the 150). Preview may include it as an **explicit extra**. Do not invent production IDs for Đúng rồi / Thử lại / じょうず.",
        "",
        "## HUMAN_REQUIRED replacement list",
        "",
        "| id | lang | spokenText | path | duration_ms | sample_rate | peak_db |",
        "|---|---|---|---|---|---|---|",
    ]
    for src in required:
        inv = inv_by.get(src["id"], {})
        rec_item = rec_by.get(src["id"], {})
        spoken = rec_item.get("pronunciation_note") or src["text"]
        lines.append(
            f"| `{src['id']}` | {src['language']} | {spoken} | `{src['asset']}` | {inv.get('duration_ms','')} | {inv.get('sample_rate','')} | {inv.get('peak_db','')} |"
        )
    lines.extend(
        [
            "",
            "## Curriculum vs naive letter chart",
            "",
            "User-facing examples such as Â→ớ or B→bờ as a **name** are **not** how this app currently teaches.",
            "Runtime catalog (`vietnamese_speech_catalog.dart`): B name=`bê`, B sound=`bờ`; Â name/sound=`â`. V3 spokenText preserves that.",
            "Preview may include extra pedagogy samples (`á`, `ớ`) that are **not** production letter IDs.",
            "",
            "## Provider discovery (this environment)",
            "",
            "- Revid MCP/API: **not available** (Cursor dynamic tools: `cursor` namespace only).",
            "- No voice IDs discovered.",
            "- Credentials: environment variables only. See `tool/.env.audio.v3.example`.",
            "",
        ]
    )
    (ROOT / "tool" / "audio_v3_preflight.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {out} items={len(items)}")
    print(f"Wrote tool/audio_v3_preflight.md rows={len(required)}")


if __name__ == "__main__":
    main()
